theme="onedark"
[editor]
bufferline = "always"
auto-save = true
[editor.statusline]
center = ["version-control"]
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
n = "move_line_down"
e = "move_line_up"
C-e = "goto_next_buffer"

[keys.insert.t]
g = "normal_mode"

[keys.select]
n = "extend_line_down"
e = "extend_line_up"